# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme
- jekyll-polyglot

# Site settings
url: 'https://logandikov.wedding'
baseurl: ''
title: "Catriona & Pavel's wedding"
description: "Catriona & Pavel's wedding"
permalink: pretty
logo: null

# Header nav
nav_menu:
  en: Menu
  bg: Меню

navigation_header:
- title:
    en: Home
    bg: Начало
  url: /
- title:
    en: Timeline
    bg: График
  url: /timeline
- title:
    en: Travel & accommodation
    bg: Транспорт и настаняване
  url: /travel
- title:
    en: Registry
    bg: Списък
  url: /registry
- title:
    en: FAQ
    bg: ЧЗВ
  url: /faq
- title:
    en: RSVP
    bg: Отговор
  url: /rsvp

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


languages: ["en", "bg"]
langsep: '<br />'
language_names:
  en: English
  bg: Български
default_lang: "en"
exclude_from_localizations: ["assets"]
parallel_localization: false   # to support windoze